# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(823, 615)
        Form.setStyleSheet("")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 10, 820, 600))
        self.frame.setStyleSheet("QFrame#frame{\n"
"background-color: rgb(44, 47, 51);\n"
"border-radius:10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.exitButton = QtWidgets.QPushButton(self.frame)
        self.exitButton.setGeometry(QtCore.QRect(800, 10, 15, 15))
        self.exitButton.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(44, 47, 51);;\n"
"    color: rgb(185, 187, 190);\n"
"    font: 10pt \"Terminal\";\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(60, 64, 71);\n"
"    color: rgb(216, 217, 218);\n"
"    font: 10pt \"Terminal\";\n"
"}")
        self.exitButton.setObjectName("exitButton")
        self.minimizeButton = QtWidgets.QPushButton(self.frame)
        self.minimizeButton.setGeometry(QtCore.QRect(780, 12, 15, 15))
        self.minimizeButton.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(44, 47, 51);;\n"
"    color: rgb(185, 187, 190);\n"
"    font: 10pt \"Terminal\";\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(60, 64, 71);\n"
"    color: rgb(216, 217, 218);\n"
"    font: 10pt \"Terminal\";\n"
"}")
        self.minimizeButton.setObjectName("minimizeButton")
        self.loadButton = QtWidgets.QPushButton(self.frame)
        self.loadButton.setEnabled(True)
        self.loadButton.setGeometry(QtCore.QRect(10, 530, 60, 60))
        self.loadButton.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(35, 39, 42);\n"
"    color: rgb(185, 187, 190);\n"
"    font: 10pt \"Terminal\";\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(60, 64, 71);\n"
"    color: rgb(216, 217, 218);\n"
"    font: 10pt \"Terminal\";\n"
"}")
        self.loadButton.setObjectName("loadButton")
        self.pasteButton = QtWidgets.QPushButton(self.frame)
        self.pasteButton.setGeometry(QtCore.QRect(80, 530, 60, 60))
        self.pasteButton.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(35, 39, 42);\n"
"    color: rgb(185, 187, 190);\n"
"    font: 10pt \"Terminal\";\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(60, 64, 71);\n"
"    color: rgb(216, 217, 218);\n"
"    font: 10pt \"Terminal\";\n"
"}")
        self.pasteButton.setObjectName("pasteButton")
        self.imageWidget = QtWidgets.QLabel(self.frame)
        self.imageWidget.setEnabled(True)
        self.imageWidget.setGeometry(QtCore.QRect(10, 40, 370, 480))
        self.imageWidget.setStyleSheet("QLabel{\n"
"    font: 81 8pt \"Rockwell Extra Bold\";\n"
"    border-radius: 10px;\n"
"    background-color: rgb(60, 64, 71);\n"
"    color: rgb(216, 217, 218);\n"
"    \n"
"    font: 75 72pt \"MS Shell Dlg 2\";\n"
"}")
        self.imageWidget.setText("")
        self.imageWidget.setPixmap(QtGui.QPixmap("../VSprojects/proekt/out/rdraw.png"))
        self.imageWidget.setWordWrap(False)
        self.imageWidget.setOpenExternalLinks(False)
        self.imageWidget.setObjectName("imageWidget")
        self.saveButton = QtWidgets.QPushButton(self.frame)
        self.saveButton.setGeometry(QtCore.QRect(440, 530, 91, 60))
        self.saveButton.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(35, 39, 42);\n"
"    color: rgb(185, 187, 190);\n"
"    font: 10pt \"Terminal\";\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(60, 64, 71);\n"
"    color: rgb(216, 217, 218);\n"
"    font: 10pt \"Terminal\";\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.copyButton = QtWidgets.QPushButton(self.frame)
        self.copyButton.setEnabled(True)
        self.copyButton.setGeometry(QtCore.QRect(541, 530, 60, 60))
        self.copyButton.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(35, 39, 42);\n"
"    color: rgb(185, 187, 190);\n"
"    font: 10pt \"Terminal\";\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(60, 64, 71);\n"
"    color: rgb(216, 217, 218);\n"
"    font: 10pt \"Terminal\";\n"
"}")
        self.copyButton.setObjectName("copyButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setGeometry(QtCore.QRect(439, 40, 370, 480))
        self.plainTextEdit.setStyleSheet("QPlainTextEdit{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(60, 64, 71);\n"
"    color: rgb(216, 217, 218);\n"
"    font: 15pt \"Fixedsysl\";\n"
"}\n"
"QPlainTextEdit QScrollBar:vertical {\n"
"    \n"
"\n"
"    background:rgb(60, 64, 71);\n"
"    width:10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"QPlainTextEdit QScrollBar::handle:vertical {\n"
"    border: 1px solid rgb(255, 255, 0);\n"
"    background:rgb(185, 187, 190)\n"
"    \n"
"}")
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setBackgroundVisible(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalFrame = QtWidgets.QFrame(self.frame)
        self.horizontalFrame.setEnabled(True)
        self.horizontalFrame.setGeometry(QtCore.QRect(290, 500, 258, 52))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.errorMessage = QtWidgets.QLabel(self.horizontalFrame)
        self.errorMessage.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errorMessage.sizePolicy().hasHeightForWidth())
        self.errorMessage.setSizePolicy(sizePolicy)
        self.errorMessage.setStyleSheet("QLabel{\n"
"    \n"
"    border-radius: 10px;\n"
"    background-color:rgb(236, 66, 69);\n"
"    color: rgb(216, 217, 218);\n"
"    padding-left: auto;\n"
"    padding-right: auto;\n"
"    font: 8pt \"Terminal\";\n"
"    \n"
"}\n"
"QLabel:disabled{\n"
"     background-color:rgba(0, 0, 0, 0);\n"
"    color: rgba(216, 217, 218,0);\n"
"}")
        self.errorMessage.setObjectName("errorMessage")
        self.horizontalLayout.addWidget(self.errorMessage)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.saveMessage = QtWidgets.QLabel(self.frame)
        self.saveMessage.setEnabled(False)
        self.saveMessage.setGeometry(QtCore.QRect(350, 511, 131, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveMessage.sizePolicy().hasHeightForWidth())
        self.saveMessage.setSizePolicy(sizePolicy)
        self.saveMessage.setStyleSheet("QLabel{\n"
"    \n"
"    border-radius: 10px;\n"
"    background-color: rgb(35, 39, 42);\n"
"    color: rgb(216, 217, 218);\n"
"    padding-left: auto;\n"
"    padding-right: auto;\n"
"    font: 8pt \"Terminal\";\n"
"    \n"
"}\n"
"QLabel:disabled{\n"
"     background-color:rgba(0, 0, 0, 0);\n"
"    color: rgba(216, 217, 218,0);\n"
"}")
        self.saveMessage.setObjectName("saveMessage")
        self.loadgif = QtWidgets.QLabel(self.frame)
        self.loadgif.setEnabled(False)
        self.loadgif.setGeometry(QtCore.QRect(385, 280, 55, 51))
        self.loadgif.setText("")
        self.loadgif.setObjectName("loadgif")
        self.copyMessage = QtWidgets.QLabel(self.frame)
        self.copyMessage.setEnabled(False)
        self.copyMessage.setGeometry(QtCore.QRect(340, 511, 141, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyMessage.sizePolicy().hasHeightForWidth())
        self.copyMessage.setSizePolicy(sizePolicy)
        self.copyMessage.setStyleSheet("QLabel{\n"
"    \n"
"    border-radius: 10px;\n"
"    background-color: rgb(35, 39, 42);\n"
"    color: rgb(216, 217, 218);\n"
"    padding-left: auto;\n"
"    padding-right: auto;\n"
"    font: 8pt \"Terminal\";\n"
"    \n"
"}\n"
"QLabel:disabled{\n"
"     background-color:rgba(0, 0, 0, 0);\n"
"    color: rgba(216, 217, 218,0);\n"
"}")
        self.copyMessage.setObjectName("copyMessage")
        self.codeMode = QtWidgets.QPushButton(self.frame)
        self.codeMode.setEnabled(True)
        self.codeMode.setGeometry(QtCore.QRect(610, 530, 60, 60))
        self.codeMode.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(35, 39, 42);\n"
"    color: rgb(185, 187, 190);\n"
"    font: 10pt \"Terminal\";\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(60, 64, 71);\n"
"    color: rgb(216, 217, 218);\n"
"    font: 10pt \"Terminal\";\n"
"}")
        self.codeMode.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/roske/Pictures/code.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.codeMode.setIcon(icon)
        self.codeMode.setIconSize(QtCore.QSize(70, 70))
        self.codeMode.setObjectName("codeMode")
        self.tabMode = QtWidgets.QPushButton(self.frame)
        self.tabMode.setEnabled(True)
        self.tabMode.setGeometry(QtCore.QRect(680, 530, 60, 60))
        self.tabMode.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(35, 39, 42);\n"
"    color: rgb(185, 187, 190);\n"
"    font: 10pt \"Terminal\";\n"
"}\n"
"QPushButton:hover{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(60, 64, 71);\n"
"    color: rgb(216, 217, 218);\n"
"    font: 10pt \"Terminal\";\n"
"}")
        self.tabMode.setIconSize(QtCore.QSize(70, 70))
        self.tabMode.setObjectName("tabMode")
        self.codeModeMessage = QtWidgets.QLabel(self.frame)
        self.codeModeMessage.setEnabled(False)
        self.codeModeMessage.setGeometry(QtCore.QRect(340, 510, 141, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.codeModeMessage.sizePolicy().hasHeightForWidth())
        self.codeModeMessage.setSizePolicy(sizePolicy)
        self.codeModeMessage.setStyleSheet("QLabel{\n"
"    \n"
"    border-radius: 10px;\n"
"    background-color: rgb(35, 39, 42);\n"
"    color: rgb(216, 217, 218);\n"
"    padding-left: auto;\n"
"    padding-right: auto;\n"
"    font: 8pt \"Terminal\";\n"
"    \n"
"}\n"
"QLabel:disabled{\n"
"     background-color:rgba(0, 0, 0, 0);\n"
"    color: rgba(216, 217, 218,0);\n"
"}")
        self.codeModeMessage.setObjectName("codeModeMessage")
        self.textModeMessage = QtWidgets.QLabel(self.frame)
        self.textModeMessage.setEnabled(False)
        self.textModeMessage.setGeometry(QtCore.QRect(350, 510, 121, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textModeMessage.sizePolicy().hasHeightForWidth())
        self.textModeMessage.setSizePolicy(sizePolicy)
        self.textModeMessage.setStyleSheet("QLabel{\n"
"    \n"
"    border-radius: 10px;\n"
"    background-color: rgb(35, 39, 42);\n"
"    color: rgb(216, 217, 218);\n"
"    padding-left: auto;\n"
"    padding-right: auto;\n"
"    font: 8pt \"Terminal\";\n"
"    \n"
"}\n"
"QLabel:disabled{\n"
"     background-color:rgba(0, 0, 0, 0);\n"
"    color: rgba(216, 217, 218,0);\n"
"}")
        self.textModeMessage.setObjectName("textModeMessage")
        self.plainTextEdit.raise_()
        self.exitButton.raise_()
        self.minimizeButton.raise_()
        self.loadButton.raise_()
        self.pasteButton.raise_()
        self.imageWidget.raise_()
        self.saveButton.raise_()
        self.copyButton.raise_()
        self.horizontalFrame.raise_()
        self.saveMessage.raise_()
        self.loadgif.raise_()
        self.copyMessage.raise_()
        self.codeMode.raise_()
        self.tabMode.raise_()
        self.codeModeMessage.raise_()
        self.textModeMessage.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.exitButton.setText(_translate("Form", "x"))
        self.minimizeButton.setText(_translate("Form", "-"))
        self.loadButton.setText(_translate("Form", "Load"))
        self.pasteButton.setText(_translate("Form", "Paste"))
        self.saveButton.setText(_translate("Form", "Save as"))
        self.copyButton.setText(_translate("Form", "Copy"))
        self.errorMessage.setText(_translate("Form", "Is not picture"))
        self.saveMessage.setText(_translate("Form", "Saved"))
        self.copyMessage.setText(_translate("Form", "Copied"))
        self.tabMode.setText(_translate("Form", "TAB"))
        self.codeModeMessage.setText(_translate("Form", "Code"))
        self.textModeMessage.setText(_translate("Form", "Text"))
